[pytest]
testpaths = tests
filterwarnings =
    ignore::pytest.PytestConfigWarning
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::DeprecationWarning
    ignore::UserWarning:pydantic.*
